### ISSUE TITLE
score value with city batch geocoder

### ISSUE THREAD

**Issue by chris-prener** [slu-openGIS/gateway#13]
score not being returned for the city batch geocoder, even when it is hard coded in as `100`

**Comment by chris-prener** [comment]
occasionally, the city batch geocoder also doesn't pass the matched address for some reason...

**Comment by walker** [comment]
Super-weird. This is an Esri ArcServer. It's configured pretty vanilla, as well. I'll look to see how your code is using it and see if I can't provide API parameters to make the return values predictable.

**Comment by walker** [comment]
Also, just noting, but your code is still not on the v4 geocoder. The one referenced is getting a bit long in the tooth.

**Comment by walker** [comment]
- Use "SingleLine" with our geocoder.
- Don't ever provide city, state, zip (if possible) -- only street num & street name.

Here's the addresses payload example that gets the right response:
```
{"records": [
        {
            "attributes": {
                "SingleLine": "1520 Market St"
            }
        },
        {
            "attributes": {
                "SingleLine": "1200 Market St"
            }
        }
]}
```

Edit: turns out you don't need to provide the Object ID.

**Comment by chris-prener** [comment]
Thanks @walker - I think it is an issue with our code and not the city's tooling in this case. Will make that update to the more recent geocoder and will let you know what I find!

**Comment by chris-prener** [comment]
Updated to `maps6.stlouis-mo.gov` as of today. @walker - how often are these changed?

**Comment by walker** [comment]
@chris-prener We're hoping to automate the re-build of those geocoders in-place, on a weekly basis, so that there's no more versioning in the URLs. Maps6 should be our primary ArcServer for the time being.

**Comment by chris-prener** [comment]
awesome! thanks for keeping us posted @walker
